version: '3.9'
services:
  
  crawler:
    build: 
      context: ./
      dockerfile: ./docker/crawler/Dockerfile
    volumes:
      - .:/app
      
  analysis:
    build: 
      context: ./
      dockerfile: ./docker/analysis/Dockerfile
    volumes:
      - .:/app
    environment:
      - PASSWORD=password
    ports:
      - "8787:8787"
      
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      
volumes:
  dbdata: